[build]
  publish = "/"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "node server.js"
  port = 3999          # puerto del proxy Netlify CLI
  targetPort = 3000    # puerto interno del server Express
  autoLaunch = false
